Turn off jasypt initialization vector by default (#5025)

diff --git a/.github/workflows/cas-build.yml b/.github/workflows/cas-build.yml
--- a/.github/workflows/cas-build.yml
+++ b/.github/workflows/cas-build.yml
@@ -289,7 +289,10 @@ jobs:
       - name: Validate CAS Command-line Shell
         run: |
           casVersion=$(./gradlew casVersion --no-daemon -q)
-          java -jar support/cas-server-support-shell/build/libs/cas-server-support-shell-${casVersion}.jar @ci/tests/shell/cas-shell-script.sh
+          java -jar support/cas-server-support-shell/build/libs/cas-server-support-shell-${casVersion}.jar @ci/tests/shell/cas-shell-script.sh 2>&1 | tee cas-shell.out
+          echo "Checking for stack traces in output that would indicate an error"
+          count=$(grep -c cas-server-support-shell cas-shell.out || true)
+          test $count -eq 0
 
 ##########################################################################
 
